/**
 * Callback and Related APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.000.19.016
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PushTarget'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PushTarget'));
  } else {
    // Browser globals (root is window)
    if (!root.CallbackAndRelatedApIs) {
      root.CallbackAndRelatedApIs = {};
    }
    root.CallbackAndRelatedApIs.CreateCallbackParms = factory(root.CallbackAndRelatedApIs.ApiClient, root.CallbackAndRelatedApIs.PushTarget);
  }
}(this, function(ApiClient, PushTarget) {
  'use strict';




  /**
   * The CreateCallbackParms model module.
   * @module model/CreateCallbackParms
   * @version 3.0.000.19.016
   */

  /**
   * Constructs a new <code>CreateCallbackParms</code>.
   * @alias module:model/CreateCallbackParms
   * @class
   * @param serviceName {String} Name of the callback execution service provisioned in GES.
   * @param phoneNumber {String} Number to call back.
   */
  var exports = function(serviceName, phoneNumber) {
    var _this = this;

    _this['serviceName'] = serviceName;
    _this['phoneNumber'] = phoneNumber;















  };

  /**
   * Constructs a <code>CreateCallbackParms</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCallbackParms} obj Optional instance to populate.
   * @return {module:model/CreateCallbackParms} The populated <code>CreateCallbackParms</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('serviceName')) {
        obj['serviceName'] = ApiClient.convertToType(data['serviceName'], 'String');
      }
      if (data.hasOwnProperty('phoneNumber')) {
        obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
      }
      if (data.hasOwnProperty('desiredTime')) {
        obj['desiredTime'] = ApiClient.convertToType(data['desiredTime'], 'Date');
      }
      if (data.hasOwnProperty('cbOfferType')) {
        obj['cbOfferType'] = ApiClient.convertToType(data['cbOfferType'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], 'String');
      }
      if (data.hasOwnProperty('inboundVQ')) {
        obj['inboundVQ'] = ApiClient.convertToType(data['inboundVQ'], 'String');
      }
      if (data.hasOwnProperty('offerThreshold')) {
        obj['offerThreshold'] = ApiClient.convertToType(data['offerThreshold'], 'Number');
      }
      if (data.hasOwnProperty('channel')) {
        obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
      }
      if (data.hasOwnProperty('offerTiming')) {
        obj['offerTiming'] = ApiClient.convertToType(data['offerTiming'], 'String');
      }
      if (data.hasOwnProperty('cbOriginationIxnId')) {
        obj['cbOriginationIxnId'] = ApiClient.convertToType(data['cbOriginationIxnId'], 'String');
      }
      if (data.hasOwnProperty('surveyRP')) {
        obj['surveyRP'] = ApiClient.convertToType(data['surveyRP'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('routePoint')) {
        obj['routePoint'] = ApiClient.convertToType(data['routePoint'], 'String');
      }
      if (data.hasOwnProperty('userData')) {
        obj['userData'] = ApiClient.convertToType(data['userData'], {'String': Object});
      }
      if (data.hasOwnProperty('captchaToken')) {
        obj['captchaToken'] = ApiClient.convertToType(data['captchaToken'], 'String');
      }
      if (data.hasOwnProperty('pushTargets')) {
        obj['pushTargets'] = ApiClient.convertToType(data['pushTargets'], [PushTarget]);
      }
      if (data.hasOwnProperty('alwaysCheckCapacity')) {
        obj['alwaysCheckCapacity'] = ApiClient.convertToType(data['alwaysCheckCapacity'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Name of the callback execution service provisioned in GES.
   * @member {String} serviceName
   */
  exports.prototype['serviceName'] = undefined;
  /**
   * Number to call back.
   * @member {String} phoneNumber
   */
  exports.prototype['phoneNumber'] = undefined;
  /**
   * Desired time to have the callback. By default, the desired time is the current time. This option format is ISO 8601 yyyy-MM-ddTHH:mm:ss.SSSZ such as 2013-05-28T15:30:00.000Z.
   * @member {Date} desiredTime
   */
  exports.prototype['desiredTime'] = undefined;
  /**
   * Type of callback that was originally offered and accepted by the customer. Possible values are ASAP, SCHEDULED, COMBINED_SCHEDULED_AND_ASAP. Note that this is used for reporting purposes only.
   * @member {String} cbOfferType
   * @default 'ASAP if the request does not include the desiredTime parameter and SCHEDULED if the request includes the desiredTime parameter.'
   */
  exports.prototype['cbOfferType'] = 'ASAP if the request does not include the desiredTime parameter and SCHEDULED if the request includes the desiredTime parameter.';
  /**
   * Preferred language for voice prompts in Designer's format. It needs to be in the ISO-639-1 format for the first part (indicating the language) and the ISO Alpha-2 code for the second part (indicating the region which speaks the language). Please check in Designer System Variables under Language for the list of supported values. Here are some sample values, en-US, en-UK, fr-FR, fr-CA, es-ES, es-MX.
   * @member {String} language
   * @default 'en-US'
   */
  exports.prototype['language'] = 'en-US';
  /**
   * The name of the inbound virtual queue the call would have been placed in if the caller did not accept the callback. This is for reporting the estimated wait time for the inbound virtual queue.
   * @member {String} inboundVQ
   */
  exports.prototype['inboundVQ'] = undefined;
  /**
   * This is the estimated wait time threshold (in seconds) that was used to determine when callback should be offered.
   * @member {Number} offerThreshold
   */
  exports.prototype['offerThreshold'] = undefined;
  /**
   * Callback origination channel.
   * @member {String} channel
   */
  exports.prototype['channel'] = undefined;
  /**
   * OFF-HOURS when callback (typically scheduled only) was offered outside business hours, ON-HOURS when callback was offered during business hours. If not passed in, then default value is <unspecified>.
   * @member {String} offerTiming
   */
  exports.prototype['offerTiming'] = undefined;
  /**
   * The Call ID (CallUUID) of the inbound call where callback was offered originally and accepted. For chat scenarios this should be chat interaction id. If not passed in, then default value is <unspecified>\".
   * @member {String} cbOriginationIxnId
   */
  exports.prototype['cbOriginationIxnId'] = undefined;
  /**
   * After the callback is complete, the user can be routed to a survey application to provide feedback. If passed in, this will override the value configured in the CALLBACK_SETTINGS data table.
   * @member {String} surveyRP
   */
  exports.prototype['surveyRP'] = undefined;
  /**
   * The initial priority of the call when placed in the virtual queue. This will override the value configured in the Callback V2 block's UI if passed in. The other values configured in the Callback V2 block's UI for priority (priority increments and priority limits) will not be modified.
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * Routing point to use when making an outbound call. This will override the value configured in the CALLBACK_SETTINGS data table if passed in.
   * @member {String} routePoint
   */
  exports.prototype['routePoint'] = undefined;
  /**
   * A hash map of user-specific data that will be associated with the callback. Use hash key names that are considered valid JavaScript variable names - otherwise they will be ignored. For privacy reason, all contents of the user data will not be written to the application logs.
   * @member {Object.<String, Object>} userData
   */
  exports.prototype['userData'] = undefined;
  /**
   * The response key generated from the user's captcha interaction. Required if captcha validation is required for the tenant.
   * @member {String} captchaToken
   */
  exports.prototype['captchaToken'] = undefined;
  /**
   * An array of push notification channels and targets that will receive a push notification. This is required when serviceName is configured to be USERORIGINATED, optional when it is USERTERMINATED.
   * @member {Array.<module:model/PushTarget>} pushTargets
   */
  exports.prototype['pushTargets'] = undefined;
  /**
   * Changes handling of capacity checks to prevent scheduled callbacks from being pushed into another time slot. Scheduled callbacks that are likely not to be handled by the capacity bucket specified by the desiredTime are rejected. This option also treats all callbacks with a desiredTime as a scheduled callback.
   * @member {Boolean} alwaysCheckCapacity
   */
  exports.prototype['alwaysCheckCapacity'] = undefined;



  return exports;
}));


