/**
 * Callback and Related APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.000.19.011
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CallbackAndRelatedApIs) {
      root.CallbackAndRelatedApIs = {};
    }
    root.CallbackAndRelatedApIs.VerifyCaptchaParms = factory(root.CallbackAndRelatedApIs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VerifyCaptchaParms model module.
   * @module model/VerifyCaptchaParms
   * @version 3.0.000.19.011
   */

  /**
   * Constructs a new <code>VerifyCaptchaParms</code>.
   * @alias module:model/VerifyCaptchaParms
   * @class
   * @param siteKey {String} The public site key for the captcha widget.
   * @param captchaToken {String} The response key generated from the user's captcha interaction.
   */
  var exports = function(siteKey, captchaToken) {
    var _this = this;

    _this['siteKey'] = siteKey;
    _this['captchaToken'] = captchaToken;
  };

  /**
   * Constructs a <code>VerifyCaptchaParms</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerifyCaptchaParms} obj Optional instance to populate.
   * @return {module:model/VerifyCaptchaParms} The populated <code>VerifyCaptchaParms</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('siteKey')) {
        obj['siteKey'] = ApiClient.convertToType(data['siteKey'], 'String');
      }
      if (data.hasOwnProperty('captchaToken')) {
        obj['captchaToken'] = ApiClient.convertToType(data['captchaToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * The public site key for the captcha widget.
   * @member {String} siteKey
   */
  exports.prototype['siteKey'] = undefined;
  /**
   * The response key generated from the user's captcha interaction.
   * @member {String} captchaToken
   */
  exports.prototype['captchaToken'] = undefined;



  return exports;
}));


