/**
 * Callback and Related APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.000.19
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VerifyCaptchaParms', 'model/VerifyCaptchaResponse200', 'model/VerifyCaptchaResponse400', 'model/VerifyCaptchaResponse500'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/VerifyCaptchaParms'), require('../model/VerifyCaptchaResponse200'), require('../model/VerifyCaptchaResponse400'), require('../model/VerifyCaptchaResponse500'));
  } else {
    // Browser globals (root is window)
    if (!root.CallbackAndRelatedApIs) {
      root.CallbackAndRelatedApIs = {};
    }
    root.CallbackAndRelatedApIs.CaptchaApi = factory(root.CallbackAndRelatedApIs.ApiClient, root.CallbackAndRelatedApIs.VerifyCaptchaParms, root.CallbackAndRelatedApIs.VerifyCaptchaResponse200, root.CallbackAndRelatedApIs.VerifyCaptchaResponse400, root.CallbackAndRelatedApIs.VerifyCaptchaResponse500);
  }
}(this, function(ApiClient, VerifyCaptchaParms, VerifyCaptchaResponse200, VerifyCaptchaResponse400, VerifyCaptchaResponse500) {
  'use strict';

  /**
   * Captcha service.
   * @module api/CaptchaApi
   * @version 3.0.000.19
   */

  /**
   * Constructs a new CaptchaApi. 
   * @alias module:api/CaptchaApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Verifies a captcha token.
     * Checks provisioned Captcha.
     * @param {String} xApiKey API Key
     * @param {module:model/VerifyCaptchaParms} body Callback properties.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/VerifyCaptchaResponse200} and HTTP response
     */
    this.verifyCaptchaExternalWithHttpInfo = function(xApiKey, body) {
      var postBody = body;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling verifyCaptchaExternal");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling verifyCaptchaExternal");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'x-api-key': xApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = VerifyCaptchaResponse200;

      return this.apiClient.callApi(
        '/captcha/verify', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Verifies a captcha token.
     * Checks provisioned Captcha.
     * @param {String} xApiKey API Key
     * @param {module:model/VerifyCaptchaParms} body Callback properties.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/VerifyCaptchaResponse200}
     */
    this.verifyCaptchaExternal = function(xApiKey, body) {
      return this.verifyCaptchaExternalWithHttpInfo(xApiKey, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
