/**
 * Callback and Related APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.000.19
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NotificationPublishParms', 'model/NotificationPublishResponse200', 'model/NotificationPublishResponse400', 'model/NotificationPublishResponse500'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/NotificationPublishParms'), require('../model/NotificationPublishResponse200'), require('../model/NotificationPublishResponse400'), require('../model/NotificationPublishResponse500'));
  } else {
    // Browser globals (root is window)
    if (!root.CallbackAndRelatedApIs) {
      root.CallbackAndRelatedApIs = {};
    }
    root.CallbackAndRelatedApIs.NotificationApi = factory(root.CallbackAndRelatedApIs.ApiClient, root.CallbackAndRelatedApIs.NotificationPublishParms, root.CallbackAndRelatedApIs.NotificationPublishResponse200, root.CallbackAndRelatedApIs.NotificationPublishResponse400, root.CallbackAndRelatedApIs.NotificationPublishResponse500);
  }
}(this, function(ApiClient, NotificationPublishParms, NotificationPublishResponse200, NotificationPublishResponse400, NotificationPublishResponse500) {
  'use strict';

  /**
   * Notification service.
   * @module api/NotificationApi
   * @version 3.0.000.19
   */

  /**
   * Constructs a new NotificationApi. 
   * @alias module:api/NotificationApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Sends provided notification to Firebase cloud Messaging.
     * Retrieves Firebase credentials from Tenant KVP entries. Fetches Oauth token from Google. Sends provided notification to Firebase cloud Messaging to be delivered to the specified recipient.
     * @param {String} xApiKey API Key. For example,  Z2y9eiTiQZ4ceKNpxy1YAarhpvxJXPCj4rFrbVep
     * @param {module:model/NotificationPublishParms} body Request properties.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/NotificationPublishResponse200} and HTTP response
     */
    this.notificationPublishWithHttpInfo = function(xApiKey, body) {
      var postBody = body;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling notificationPublish");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling notificationPublish");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'x-api-key': xApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = NotificationPublishResponse200;

      return this.apiClient.callApi(
        '/notification/publish', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Sends provided notification to Firebase cloud Messaging.
     * Retrieves Firebase credentials from Tenant KVP entries. Fetches Oauth token from Google. Sends provided notification to Firebase cloud Messaging to be delivered to the specified recipient.
     * @param {String} xApiKey API Key. For example,  Z2y9eiTiQZ4ceKNpxy1YAarhpvxJXPCj4rFrbVep
     * @param {module:model/NotificationPublishParms} body Request properties.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/NotificationPublishResponse200}
     */
    this.notificationPublish = function(xApiKey, body) {
      return this.notificationPublishWithHttpInfo(xApiKey, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
