/**
 * Callback and Related APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.000.19.015
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QueueStatusResponse200', 'model/QueueStatusResponse400', 'model/QueueStatusResponse500'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/QueueStatusResponse200'), require('../model/QueueStatusResponse400'), require('../model/QueueStatusResponse500'));
  } else {
    // Browser globals (root is window)
    if (!root.CallbackAndRelatedApIs) {
      root.CallbackAndRelatedApIs = {};
    }
    root.CallbackAndRelatedApIs.QueueStatusApi = factory(root.CallbackAndRelatedApIs.ApiClient, root.CallbackAndRelatedApIs.QueueStatusResponse200, root.CallbackAndRelatedApIs.QueueStatusResponse400, root.CallbackAndRelatedApIs.QueueStatusResponse500);
  }
}(this, function(ApiClient, QueueStatusResponse200, QueueStatusResponse400, QueueStatusResponse500) {
  'use strict';

  /**
   * QueueStatus service.
   * @module api/QueueStatusApi
   * @version 3.0.000.19.015
   */

  /**
   * Constructs a new QueueStatusApi. 
   * @alias module:api/QueueStatusApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Gets the queue&#39;s readiness for callbacks.
     * Retrieves the estimated-wait-time and whether the queue accepts immediate and/or scheduled callbacks.
     * @param {String} xApiKey API Key. For example,  Z2y9eiTiQZ4ceKNpxy1YAarhpvxJXPCj4rFrbVep
     * @param {String} queueName Name of the callback queue.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/QueueStatusResponse200} and HTTP response
     */
    this.queryQueueStatusWithHttpInfo = function(xApiKey, queueName) {
      var postBody = null;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling queryQueueStatus");
      }

      // verify the required parameter 'queueName' is set
      if (queueName === undefined || queueName === null) {
        throw new Error("Missing the required parameter 'queueName' when calling queryQueueStatus");
      }


      var pathParams = {
        'queue-name': queueName
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'x-api-key': xApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = QueueStatusResponse200;

      return this.apiClient.callApi(
        '/callbacks/queue-status/{queue-name}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets the queue&#39;s readiness for callbacks.
     * Retrieves the estimated-wait-time and whether the queue accepts immediate and/or scheduled callbacks.
     * @param {String} xApiKey API Key. For example,  Z2y9eiTiQZ4ceKNpxy1YAarhpvxJXPCj4rFrbVep
     * @param {String} queueName Name of the callback queue.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/QueueStatusResponse200}
     */
    this.queryQueueStatus = function(xApiKey, queueName) {
      return this.queryQueueStatusWithHttpInfo(xApiKey, queueName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
