/**
 * Callback and Related APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 9.0.18
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CallbackAndRelatedApIs);
  }
}(this, function(expect, CallbackAndRelatedApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CallbackAndRelatedApIs.CallInRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CallInRequest', function() {
    it('should create an instance of CallInRequest', function() {
      // uncomment below and update the code to test CallInRequest
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be.a(CallbackAndRelatedApIs.CallInRequest);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

    it('should have the property toPhoneNumber (base name: "toPhoneNumber")', function() {
      // uncomment below and update the code to test the property toPhoneNumber
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupName (base name: "groupName")', function() {
      // uncomment below and update the code to test the property groupName
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

    it('should have the property expirationTime (base name: "expirationTime")', function() {
      // uncomment below and update the code to test the property expirationTime
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

    it('should have the property accessCode (base name: "accessCode")', function() {
      // uncomment below and update the code to test the property accessCode
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

    it('should have the property fromPhoneNumber (base name: "fromPhoneNumber")', function() {
      // uncomment below and update the code to test the property fromPhoneNumber
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

    it('should have the property callbackServiceId (base name: "callbackServiceId")', function() {
      // uncomment below and update the code to test the property callbackServiceId
      //var instance = new CallbackAndRelatedApIs.CallInRequest();
      //expect(instance).to.be();
    });

  });

}));
